### ISSUE TITLE
求参考文档

### ISSUE THREAD

**Issue by BNK-ALONG** [fangyang921017/vue-jsplumb-editor#5]
作者您好，这个项目很有趣，请问有该项目的介绍文档吗？或者可以提供一下您参考的文档文献吗？谢谢您。

**Comment by lesonky** [comment]
就自己参考 jsplumb 的文档吧,之前我也弄过一个,类似的功能,但是jsplumb毕竟是dom操作,还有一些小bug,而且文档和官方demo版本还不匹配,有点坑爹

**Comment by fangyang921017** [comment]
主要参考的 jsplumb 官方文档，不过当时的官方文档已经是过期了的
